services:
  postgres:
    container_name: biwise_postgres
    image: postgres:latest
#    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - postgres_buwise:/var/lib/postgresql/data
    networks:
      - custom
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    container_name: bisie_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # command: ['/app_example/docker/app.sh']
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - custom
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8000/check_database"]
       interval: 30s
       timeout: 5s
       retries: 3


volumes:
  postgres_buwise:
    driver: local


networks:
  custom:
    driver: bridge