services:
  postgres:
    container_name: ${DOCKER_NAME}_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - postgres_buwise:/var/lib/postgresql/data
    networks:
      - custom
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    container_name: ${DOCKER_NAME}_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["/bewise/docker/app.sh"]   #  можно указать dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    networks:
      - custom
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8000/v1/check_database"]
       interval: 30s
       timeout: 5s
       retries: 3

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - custom

  zookeeper:
    platform: linux/x86_64
    container_name: ${DOCKER_NAME}-zookeeper
#    image: docker.io/bitnami/zookeeper:3.8
    image: bitnami/zookeeper:latest
    restart: unless-stopped
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - '2181:2181'
    networks:
      - custom

  kafka:
    platform: linux/x86_64
    container_name: ${DOCKER_NAME}-kafka
#    image: docker.io/bitnami/kafka:3.3
    image: bitnami/kafka:latest
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '29092:29092'  # Порт для внешнего доступа
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - custom


  kafka-ui:
    container_name: ${DOCKER_NAME}-kafka-ui
    image: provectuslabs/kafka-ui
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092  # адрес  Kafka
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181 #  адрес Zookeeper
    depends_on:
      - kafka
    networks:
      - custom

volumes:
  postgres_buwise:
    driver: local


networks:
  custom:
    driver: bridge